-- This is signal_generator_802_11n VHDL model
-- Generated by initentity script
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
USE std.textio.all;


ENTITY signal_generator_802_11n IS
    PORT( A : IN  STD_LOGIC;
          Z : OUT STD_LOGIC
        );
END signal_generator_802_11n;

ARCHITECTURE rtl OF signal_generator_802_11n IS
BEGIN
    buf:PROCESS(A)
    BEGIN
        Z<=A;
    END PROCESS;
END ARCHITECTURE;
